version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: senhasecreta
      POSTGRES_DB: meubanco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
